num_experts: 4
top_k_experts: 2
num_layers: 3
moe_layer_type: "moxe"
router_type: "conditioned_addition"
expert_type: "xlstm"
modulation_bias: "standard"
gate_bias: true
gamma: 0.7
eps: 0.0000001
difficulty_threshold: 0.9
ffn_dim: 1024
group_wise_loss: "kl_div"
post_layers_norm: false

xlstm:
  pad_token_idx: 1
  vocab_size: 49_152
  context_length: 10
  num_blocks: 1
  embedding_dim: 8
  add_post_blocks_norm: true

  mlstm_block:
    mlstm:
      conv1d_kernel_size: 4
      qkv_proj_blocksize: 16
      num_heads: 4

  slstm_block:
    slstm:
      backend: "cuda"
      num_heads: 4
      conv1d_kernel_size: 4
      bias_init: "powerlaw_blockdependent"

    feedforward:
      proj_factor: 1.7
      act_fn: "swish"
