vocab_size: 49_152
context_length: 128
num_blocks: 1
embedding_dim: 768

mlstm_block:
  mlstm:
    conv1d_kernel_size: 4
    qkv_proj_blocksize: 32
    num_heads: 8

slstm_block:
  slstm:
    backend: "cuda"
    num_heads: 8
    conv1d_kernel_size: 4
    bias_init: "powerlaw_blockdependent"
  feedforward:
    proj_factor: 1.7
    act_fn: "swish"
